/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_parson(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_parson(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_parson(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


#include "parson.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_json_set_allocation_functions(void * jarg1, void * jarg2) {
  JSON_Malloc_Function arg1 = (JSON_Malloc_Function) 0 ;
  JSON_Free_Function arg2 = (JSON_Free_Function) 0 ;
  
  arg1 = (JSON_Malloc_Function)jarg1; 
  arg2 = (JSON_Free_Function)jarg2; 
  json_set_allocation_functions(arg1,arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_parse_file(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (JSON_Value *)json_parse_file((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_parse_file_with_comments(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (JSON_Value *)json_parse_file_with_comments((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_parse_string(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (JSON_Value *)json_parse_string((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_parse_string_with_comments(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (JSON_Value *)json_parse_string_with_comments((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_json_serialization_size(void * jarg1) {
  unsigned long jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  size_t result;
  
  arg1 = (JSON_Value *)jarg1; 
  result = json_serialization_size((struct json_value_t const *)arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_serialize_to_buffer(void * jarg1, char * jarg2, unsigned long jarg3) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  JSON_Status result;
  
  arg1 = (JSON_Value *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (size_t)jarg3; 
  result = (JSON_Status)json_serialize_to_buffer((struct json_value_t const *)arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_serialize_to_file(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Value *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Status)json_serialize_to_file((struct json_value_t const *)arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_json_serialize_to_string(void * jarg1) {
  char * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  char *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (char *)json_serialize_to_string((struct json_value_t const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_json_serialization_size_pretty(void * jarg1) {
  unsigned long jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  size_t result;
  
  arg1 = (JSON_Value *)jarg1; 
  result = json_serialization_size_pretty((struct json_value_t const *)arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_serialize_to_buffer_pretty(void * jarg1, char * jarg2, unsigned long jarg3) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  JSON_Status result;
  
  arg1 = (JSON_Value *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (size_t)jarg3; 
  result = (JSON_Status)json_serialize_to_buffer_pretty((struct json_value_t const *)arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_serialize_to_file_pretty(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Value *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Status)json_serialize_to_file_pretty((struct json_value_t const *)arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_json_serialize_to_string_pretty(void * jarg1) {
  char * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  char *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (char *)json_serialize_to_string_pretty((struct json_value_t const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_json_free_serialized_string(char * jarg1) {
  char *arg1 = (char *) 0 ;
  
  arg1 = (char *)jarg1; 
  json_free_serialized_string(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_value_equals(void * jarg1, void * jarg2) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Value *arg2 = (JSON_Value *) 0 ;
  int result;
  
  arg1 = (JSON_Value *)jarg1; 
  arg2 = (JSON_Value *)jarg2; 
  result = (int)json_value_equals((struct json_value_t const *)arg1,(struct json_value_t const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_validate(void * jarg1, void * jarg2) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Value *arg2 = (JSON_Value *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Value *)jarg1; 
  arg2 = (JSON_Value *)jarg2; 
  result = (JSON_Status)json_validate((struct json_value_t const *)arg1,(struct json_value_t const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_object_get_value(void * jarg1, char * jarg2) {
  void * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Value *)json_object_get_value((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_json_object_get_string(void * jarg1, char * jarg2) {
  char * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (char *)json_object_get_string((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_object_get_object(void * jarg1, char * jarg2) {
  void * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Object *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Object *)json_object_get_object((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_object_get_array(void * jarg1, char * jarg2) {
  void * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Array *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Array *)json_object_get_array((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_json_object_get_number(void * jarg1, char * jarg2) {
  double jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  double result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (double)json_object_get_number((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_get_boolean(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)json_object_get_boolean((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_object_dotget_value(void * jarg1, char * jarg2) {
  void * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Value *)json_object_dotget_value((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_json_object_dotget_string(void * jarg1, char * jarg2) {
  char * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (char *)json_object_dotget_string((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_object_dotget_object(void * jarg1, char * jarg2) {
  void * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Object *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Object *)json_object_dotget_object((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_object_dotget_array(void * jarg1, char * jarg2) {
  void * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Array *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Array *)json_object_dotget_array((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_json_object_dotget_number(void * jarg1, char * jarg2) {
  double jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  double result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (double)json_object_dotget_number((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_dotget_boolean(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)json_object_dotget_boolean((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_json_object_get_count(void * jarg1) {
  unsigned long jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  size_t result;
  
  arg1 = (JSON_Object *)jarg1; 
  result = json_object_get_count((struct json_object_t const *)arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_json_object_get_name(void * jarg1, unsigned long jarg2) {
  char * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  size_t arg2 ;
  char *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (char *)json_object_get_name((struct json_object_t const *)arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_object_get_value_at(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  size_t arg2 ;
  JSON_Value *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (JSON_Value *)json_object_get_value_at((struct json_object_t const *)arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_object_get_wrapping_value(void * jarg1) {
  void * jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (JSON_Object *)jarg1; 
  result = (JSON_Value *)json_object_get_wrapping_value((struct json_object_t const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_has_value(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)json_object_has_value((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_has_value_of_type(void * jarg1, char * jarg2, int jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Value_Type arg3 ;
  int result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (JSON_Value_Type)jarg3; 
  result = (int)json_object_has_value_of_type((struct json_object_t const *)arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_dothas_value(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)json_object_dothas_value((struct json_object_t const *)arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_dothas_value_of_type(void * jarg1, char * jarg2, int jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Value_Type arg3 ;
  int result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (JSON_Value_Type)jarg3; 
  result = (int)json_object_dothas_value_of_type((struct json_object_t const *)arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_set_value(void * jarg1, char * jarg2, void * jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Value *arg3 = (JSON_Value *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (JSON_Value *)jarg3; 
  result = (JSON_Status)json_object_set_value(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_set_string(void * jarg1, char * jarg2, char * jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (JSON_Status)json_object_set_string(arg1,(char const *)arg2,(char const *)arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_set_number(void * jarg1, char * jarg2, double jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (double)jarg3; 
  result = (JSON_Status)json_object_set_number(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_set_boolean(void * jarg1, char * jarg2, int jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  result = (JSON_Status)json_object_set_boolean(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_set_null(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Status)json_object_set_null(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_dotset_value(void * jarg1, char * jarg2, void * jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Value *arg3 = (JSON_Value *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (JSON_Value *)jarg3; 
  result = (JSON_Status)json_object_dotset_value(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_dotset_string(void * jarg1, char * jarg2, char * jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (JSON_Status)json_object_dotset_string(arg1,(char const *)arg2,(char const *)arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_dotset_number(void * jarg1, char * jarg2, double jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (double)jarg3; 
  result = (JSON_Status)json_object_dotset_number(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_dotset_boolean(void * jarg1, char * jarg2, int jarg3) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  result = (JSON_Status)json_object_dotset_boolean(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_dotset_null(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Status)json_object_dotset_null(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_remove(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Status)json_object_remove(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_dotremove(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Status)json_object_dotremove(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_object_clear(void * jarg1) {
  int jresult ;
  JSON_Object *arg1 = (JSON_Object *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Object *)jarg1; 
  result = (JSON_Status)json_object_clear(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_array_get_value(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  JSON_Value *result = 0 ;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (JSON_Value *)json_array_get_value((struct json_array_t const *)arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_json_array_get_string(void * jarg1, unsigned long jarg2) {
  char * jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  char *result = 0 ;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (char *)json_array_get_string((struct json_array_t const *)arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_array_get_object(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  JSON_Object *result = 0 ;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (JSON_Object *)json_array_get_object((struct json_array_t const *)arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_array_get_array(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  JSON_Array *result = 0 ;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (JSON_Array *)json_array_get_array((struct json_array_t const *)arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_json_array_get_number(void * jarg1, unsigned long jarg2) {
  double jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  double result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (double)json_array_get_number((struct json_array_t const *)arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_get_boolean(void * jarg1, unsigned long jarg2) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  int result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (int)json_array_get_boolean((struct json_array_t const *)arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_json_array_get_count(void * jarg1) {
  unsigned long jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t result;
  
  arg1 = (JSON_Array *)jarg1; 
  result = json_array_get_count((struct json_array_t const *)arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_array_get_wrapping_value(void * jarg1) {
  void * jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (JSON_Array *)jarg1; 
  result = (JSON_Value *)json_array_get_wrapping_value((struct json_array_t const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_remove(void * jarg1, unsigned long jarg2) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (JSON_Status)json_array_remove(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_replace_value(void * jarg1, unsigned long jarg2, void * jarg3) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  JSON_Value *arg3 = (JSON_Value *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (JSON_Value *)jarg3; 
  result = (JSON_Status)json_array_replace_value(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_replace_string(void * jarg1, unsigned long jarg2, char * jarg3) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  char *arg3 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (char *)jarg3; 
  result = (JSON_Status)json_array_replace_string(arg1,arg2,(char const *)arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_replace_number(void * jarg1, unsigned long jarg2, double jarg3) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  double arg3 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (double)jarg3; 
  result = (JSON_Status)json_array_replace_number(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_replace_boolean(void * jarg1, unsigned long jarg2, int jarg3) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  int arg3 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (int)jarg3; 
  result = (JSON_Status)json_array_replace_boolean(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_replace_null(void * jarg1, unsigned long jarg2) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  size_t arg2 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (JSON_Status)json_array_replace_null(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_clear(void * jarg1) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  result = (JSON_Status)json_array_clear(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_append_value(void * jarg1, void * jarg2) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  JSON_Value *arg2 = (JSON_Value *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (JSON_Value *)jarg2; 
  result = (JSON_Status)json_array_append_value(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_append_string(void * jarg1, char * jarg2) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  char *arg2 = (char *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JSON_Status)json_array_append_string(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_append_number(void * jarg1, double jarg2) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  double arg2 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (double)jarg2; 
  result = (JSON_Status)json_array_append_number(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_append_boolean(void * jarg1, int jarg2) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  int arg2 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  arg2 = (int)jarg2; 
  result = (JSON_Status)json_array_append_boolean(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_array_append_null(void * jarg1) {
  int jresult ;
  JSON_Array *arg1 = (JSON_Array *) 0 ;
  JSON_Status result;
  
  arg1 = (JSON_Array *)jarg1; 
  result = (JSON_Status)json_array_append_null(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_init_object() {
  void * jresult ;
  JSON_Value *result = 0 ;
  
  result = (JSON_Value *)json_value_init_object();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_init_array() {
  void * jresult ;
  JSON_Value *result = 0 ;
  
  result = (JSON_Value *)json_value_init_array();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_init_string(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (JSON_Value *)json_value_init_string((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_init_number(double jarg1) {
  void * jresult ;
  double arg1 ;
  JSON_Value *result = 0 ;
  
  arg1 = (double)jarg1; 
  result = (JSON_Value *)json_value_init_number(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_init_boolean(int jarg1) {
  void * jresult ;
  int arg1 ;
  JSON_Value *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (JSON_Value *)json_value_init_boolean(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_init_null() {
  void * jresult ;
  JSON_Value *result = 0 ;
  
  result = (JSON_Value *)json_value_init_null();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_deep_copy(void * jarg1) {
  void * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (JSON_Value *)json_value_deep_copy((struct json_value_t const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_json_value_free(void * jarg1) {
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  json_value_free(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_value_get_type(void * jarg1) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Value_Type result;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (JSON_Value_Type)json_value_get_type((struct json_value_t const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_get_object(void * jarg1) {
  void * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Object *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (JSON_Object *)json_value_get_object((struct json_value_t const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_get_array(void * jarg1) {
  void * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Array *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (JSON_Array *)json_value_get_array((struct json_value_t const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_json_value_get_string(void * jarg1) {
  char * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  char *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (char *)json_value_get_string((struct json_value_t const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_json_value_get_number(void * jarg1) {
  double jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  double result;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (double)json_value_get_number((struct json_value_t const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_value_get_boolean(void * jarg1) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  int result;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (int)json_value_get_boolean((struct json_value_t const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_value_get_parent(void * jarg1) {
  void * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Value *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (JSON_Value *)json_value_get_parent((struct json_value_t const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_type(void * jarg1) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Value_Type result;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (JSON_Value_Type)json_type((struct json_value_t const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_object(void * jarg1) {
  void * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Object *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (JSON_Object *)json_object((struct json_value_t const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_json_array(void * jarg1) {
  void * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  JSON_Array *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (JSON_Array *)json_array((struct json_value_t const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_json_string(void * jarg1) {
  char * jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  char *result = 0 ;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (char *)json_string((struct json_value_t const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_json_number(void * jarg1) {
  double jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  double result;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (double)json_number((struct json_value_t const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_json_boolean(void * jarg1) {
  int jresult ;
  JSON_Value *arg1 = (JSON_Value *) 0 ;
  int result;
  
  arg1 = (JSON_Value *)jarg1; 
  result = (int)json_boolean((struct json_value_t const *)arg1);
  jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

